# Config for single device LoRA DPO alignment in lora_dpo_single_device.py
# using a Llama2 7B model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-2-7b-hf --output-dir /tmp/Llama-2-7b-hf --hf-token <HF_TOKEN>
#   tune download meta-llama/Llama-2-7b-hf --output-dir /scratch/gpfs/$USER/.cache/huggingface/hub/Llama-2-7b-hf --hf-token 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
# To launch on a single device, run the following command from root:
#   tune run lora_dpo_single_device --config llama2/7B_lora_dpo_single_device
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run lora_dpo_single_device --config llama2/7B_lora_dpo_single_device checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works only for training on single device.

# Model Arguments
model:
  _component_: torchtune.models.llama2.lora_llama2_7b
  lora_attn_modules: ['q_proj', 'v_proj']
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.0

# Tokenizer
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path:  /scratch/gpfs/tw6664/.cache/huggingface/hub/Llama-2-7b-hf/tokenizer.model

checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  checkpoint_dir: /scratch/gpfs/tw8948/LESS/torchtune_models/Meta-Llama-2-7B/sft
  checkpoint_files: [
    hf_model_0001_0.pt, 
    hf_model_0002_0.pt
  ]
  adapter_checkpoint: adapter_0.pt
  recipe_checkpoint: recipe_state.pt
  output_dir: ./torchtune_results/Llama-2-7b-hf/dpo_output/
  model_type: LLAMA2
resume_from_checkpoint: True

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.stack_exchanged_paired_dataset
  max_seq_len: 1024

seed: null
shuffle: True
batch_size: 2

#########################

val_dataset: 
  _component_: torchtune.datasets.stack_exchanged_paired_dataset_val
  max_seq_len: 1024

test_dataset: 
  _component_: torchtune.datasets.stack_exchanged_paired_dataset_test
  max_seq_len: 1024

val_batch_size: 16
test_batch_size: 16

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  weight_decay: 0.05
  lr: 5e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.DPOLoss
  beta: 0.1
  label_smoothing: 0
  loss_type: sigmoid

# Training
epochs: 1
max_steps_per_epoch: 10000
gradient_accumulation_steps: 1

# Logging
output_dir: ./torchtune_results/Llama-2-7b-hf/lora_dpo_output
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
log_every_n_steps: 1

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: True

# Added parameters
method: TracIN-AdaptiveSelect-PerBatch
fracinv: 2.0
result_dir: ./torchtune_dpo_results/
n_val: 80
