batch_size: 4
checkpointer:
  _component_: torchtune.utils.FullModelHFCheckpointer
  adapter_checkpoint: null
  checkpoint_dir: /scratch/gpfs/tw6664/.cache/huggingface/hub/Llama-2-7b-hf
  checkpoint_files:
  - pytorch_model-00001-of-00002.bin
  - pytorch_model-00002-of-00002.bin
  model_type: LLAMA2
  output_dir: ./torchtune_results/Llama-2-7b-hf/dpo_output/
  recipe_checkpoint: null
dataset:
  _component_: torchtune.datasets.stack_exchanged_paired_dataset
  max_seq_len: 1024
device: cuda
dtype: bf16
enable_activation_checkpointing: true
epochs: 1
fracinv: 2.0
gradient_accumulation_steps: 1
log_every_n_steps: 1
loss:
  _component_: torchtune.modules.loss.DPOLoss
  beta: 0.1
  label_smoothing: 0
  loss_type: sigmoid
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
max_steps_per_epoch: 1000
method: TracIN-AdaptiveSelect-PerBatch
metric_logger:
  _component_: torchtune.utils.metric_logging.DiskLogger
  log_dir: ${output_dir}
model:
  _component_: torchtune.models.llama2.lora_llama2_7b
  apply_lora_to_mlp: false
  apply_lora_to_output: false
  lora_alpha: 0.1
  lora_attn_modules:
  - q_proj
  - v_proj
  lora_dropout: 0.0
  lora_rank: 8
n_val: 79
optimizer:
  _component_: torch.optim.AdamW
  lr: 0.0009
  weight_decay: 0.05
output_dir: ./torchtune_results/Llama-2-7b-hf/lora_dpo_output
result_dir: ./torchtune_dpo_results/
resume_from_checkpoint: false
seed: null
shuffle: true
test_batch_size: 16
test_dataset:
  _component_: torchtune.datasets.stack_exchanged_paired_dataset_test
  max_seq_len: 1024
tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: /scratch/gpfs/tw6664/.cache/huggingface/hub/Llama-2-7b-hf/tokenizer.model
val_batch_size: 16
val_dataset:
  _component_: torchtune.datasets.stack_exchanged_paired_dataset_val
  max_seq_len: 1024
